-- Add authentication fields
ALTER TABLE "User"
    ADD COLUMN "password" TEXT NOT NULL DEFAULT '';

ALTER TABLE "User"
    ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "User"
    ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "User"
    ADD COLUMN "lastLogin" TIMESTAMP(3);

ALTER TABLE "User"
    ALTER COLUMN "password" DROP DEFAULT;
